# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Addison Howe
email: addi.howe@u.northwestern.edu
description: >- # this means to ignore newlines until "baseurl:"
  Academic webpage of Addison Howe. A work in progress for sure.
github_username:  AddisonHowe
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://addihowe.com" # the base hostname & protocol for your site, e.g. http://example.com


# Google analytics ID
google_analytics_4: G-G5S8V4DLC1


# Footer info
affiliation: >
    Addison Howe<br/>
    PhD Student<br/>
    <a href="http://www.northwestern.edu/" target="_blank">Northwestern University</a><br/>
    Engineering Sciences and Applied Mathematics

location: >
  <a href="http://www.northwestern.edu/" target="_blank">Northwestern University</a><br/>
  Northwestern University <br/>
  633 Clark St<br/>
  Evanston, IL 60208

contact: >
    <a href="mailto:addi.howe@u.northwestern.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Addison via email</a> <br/>
    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: teaching

include:
  - .htaccess
  - _pages
  - .nojekyll

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Howe
  first_name: [Addison]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
